name: Run Go Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Measure code coverage
      run: |
        go test -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Generate coverage report
      run: |
        go tool cover -html=coverage.txt -o coverage.html

    - name: Publish coverage report
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -f coverage.txt
